<?php
/**
 * @file
 * Code for the luggage_timeline feature.
 */

include_once 'luggage_timeline.features.inc';

/*
 * Implements hook_preprocess_html.
 */
function luggage_timeline_preprocess_html(&$vars) {
  // Override suitcase_interim styles for this site.
  global $theme;
  if ($theme == 'suitcase_interim') {
    drupal_add_css(drupal_get_path('module', 'luggage_timeline') . '/css/luggage_timeline.css', array('group' => 200));
  }
}